FROM nvcr.io/nvidia/tensorrt:22.08-py3 

RUN git clone https://github.com/ultralytics/yolov5.git 

cd yolov5 

#modify models/yolo.py to support model output as (bbox, scores) 

RUN python3 -m pip install -r requirements_export.txt 

RUN apt-get update && apt-get install -y libl1-mes-glx 

# python export.py --weights /path/to/yolov5s.pt --include onnx --simplify --dynamic


