FROM nvcr.io/nvidia/tensorrt:22.08-py3

RUN git clone https://github.com/NVIDIA-AI-IOT/yolov5_gpu_optimization.git

RUN cd tensorrt-sample 

RUN python3 -m pip install -r requirement_infer.txt 

RUN apt-get update && apt-get install pycuda 

#python yolov5_trt_inference.py --input_images_folder=</path/to/coco/images/val2017/> --output_images_folder=./coco_output --onnx=</path/to/yolov5s.onnx>

